# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PushNotifications' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  # Pods for PushNotifications

  target 'PushNotificationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PushNotificationsUITests' do
    # Pods for testing
  end

end
